"""add signal_outcomes

Revision ID: cda4d308bbb0
Revises: e39fbe539154
Create Date: 2026-04-30 06:26:24.133082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda4d308bbb0'
down_revision: Union[str, Sequence[str], None] = 'e39fbe539154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('signal_sources', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('price_at_signal', sa.Float(), nullable=True),
    sa.Column('price_short', sa.Float(), nullable=True),
    sa.Column('price_medium', sa.Float(), nullable=True),
    sa.Column('price_long', sa.Float(), nullable=True),
    sa.Column('outcome_short', sa.String(length=16), nullable=True),
    sa.Column('outcome_medium', sa.String(length=16), nullable=True),
    sa.Column('outcome_long', sa.String(length=16), nullable=True),
    sa.Column('evaluated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_signal_outcome_symbol_ts')
    )
    with op.batch_alter_table('signal_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_outcomes_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_so_evaluated_at', ['evaluated_at'], unique=False)
        batch_op.create_index('ix_so_signal', ['signal'], unique=False)
        batch_op.create_index('ix_so_symbol_time', ['symbol', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_so_symbol_time')
        batch_op.drop_index('ix_so_signal')
        batch_op.drop_index('ix_so_evaluated_at')
        batch_op.drop_index(batch_op.f('ix_signal_outcomes_symbol'))

    op.drop_table('signal_outcomes')
    # ### end Alembic commands ###
