"""initial_schema

Revision ID: e39fbe539154
Revises: 
Create Date: 2026-04-28 13:14:03.934189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39fbe539154'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cash_available', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('prediction_type', sa.String(length=32), nullable=False),
    sa.Column('predicted_at', sa.Integer(), nullable=False),
    sa.Column('price_at_prediction', sa.Float(), nullable=False),
    sa.Column('predicted_direction', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('time_horizon_days', sa.Integer(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('outcome_price', sa.Float(), nullable=True),
    sa.Column('outcome_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_log', schema=None) as batch_op:
        batch_op.create_index('ix_pred_symbol_time', ['symbol', 'predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_log_symbol'), ['symbol'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('ldcp', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('scraped_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_ph_symbol_time', ['symbol', 'scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_scraped_at'), ['scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_symbol'), ['symbol'], unique=False)

    op.create_table('signals_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('prev_signal', sa.String(length=16), nullable=True),
    sa.Column('signal_changed', sa.Boolean(), nullable=False),
    sa.Column('signal_sources', sa.Text(), nullable=True),
    sa.Column('action_score', sa.Float(), nullable=True),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('sma5', sa.Float(), nullable=True),
    sa.Column('sma20', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_log_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_log_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_sl_signal_time', ['signal', 'generated_at'], unique=False)
        batch_op.create_index('ix_sl_symbol_time', ['symbol', 'generated_at'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('invested_value', sa.Float(), nullable=False),
    sa.Column('total_pl', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('realized_pl', sa.Float(), nullable=False),
    sa.Column('snapshotted_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_snapshotted_at'), ['snapshotted_at'], unique=False)
        batch_op.create_index('ix_snap_portfolio_time', ['portfolio_id', 'snapshotted_at'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_buy_price', sa.Float(), nullable=False),
    sa.Column('total_invested', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_portfolio_symbol')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_pos_portfolio', ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('trade_type', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price_per_share', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('brokerage_fee', sa.Float(), nullable=False),
    sa.Column('net_value', sa.Float(), nullable=False),
    sa.Column('realized_pl', sa.Float(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trade_portfolio_time', ['portfolio_id', 'executed_at'], unique=False)
        batch_op.create_index('ix_trade_symbol_time', ['symbol', 'executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_executed_at'))
        batch_op.drop_index('ix_trade_symbol_time')
        batch_op.drop_index('ix_trade_portfolio_time')

    op.drop_table('trades')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index('ix_pos_portfolio')

    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snap_portfolio_time')
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_snapshotted_at'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('signals_log', schema=None) as batch_op:
        batch_op.drop_index('ix_sl_symbol_time')
        batch_op.drop_index('ix_sl_signal_time')
        batch_op.drop_index(batch_op.f('ix_signals_log_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_log_generated_at'))

    op.drop_table('signals_log')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_symbol'))
        batch_op.drop_index(batch_op.f('ix_price_history_scraped_at'))
        batch_op.drop_index('ix_ph_symbol_time')

    op.drop_table('price_history')
    with op.batch_alter_table('prediction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_log_symbol'))
        batch_op.drop_index('ix_pred_symbol_time')

    op.drop_table('prediction_log')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
